// TODO delete 
// MOCK


import img1 from '../../images/illustrations/1MassesWisdom.png'
import img2 from '../../images/illustrations/Tacking_note1.png'
import img3 from '../../images/illustrations/Sending emails_Monochromatic.png'
import img4 from '../../images/illustrations/SendSummaries.png'

export const MockData = [
    {
        id: 1,
        favorite: false,
        imgUrl: img1,
        title: 'My first card!',
        tags: ['Todo'],
        createdTime:'16/11/2021',
        editTime: '1/1/2022',
        likes: 100,
        autorName:'Shon Pozner',
        url: 'https://www.google.com/',
    },
    {
        id: 2,
        favorite: true,
        imgUrl: img2,
        title: 'Zoom',
        tags: ['sport', 'football', 'pop'],
        createdTime:'16/11/2021',
        editTime: '1/1/2022',
        likes: 100,
        autorName:'Shon Pozner',
        url: 'https://us02web.zoom.us/rec/play/E38eBi_rfsgGCYhh6YiiutEw4pcsdCsHF2jy0sOMCfEAEzoFrb4z0IBnQLf5jgsMRxqULz7h-5fpc5S3.tLHdrPTcTXQ2n0Tz?continueMode=true&_x_zm_rtaid=8E8g3kSeQMGVoTvDaygrrQ.1603012922993.2fcaba7a7c5cc81110b378f2474fb863&_x_zm_rhtaid=614',
    },
    {
        id: 3,
        favorite: false,
        imgUrl: img3,
        title: 'My first card!',
        tags: ['sport', 'zoom', 'imp','shon4me@gmail', 'fdasfads'],
        createdTime:'16/11/2021',
        editTime: '1/1/2022',
        likes: 100,
        autorName:'Shon Pozner',
        url: 'https://www.google.com',
    },

    {
        id: 4,
        favorite: false,
        imgUrl: img4,
        title: 'My first card!',
        tags: ['sport', 'zoom'],
        createdTime:'16/11/2021',
        editTime: '1/1/2022',
        likes: 100,
        autorName:'Shon Pozner',
        url: 'https://www.google.com/',
    },
    {
        id: 5,
        favorite: true,
        imgUrl: img1,
        title: 'My first card!',
        tags: ['Todo'],
        createdTime:'16/11/2021',
        editTime: '1/1/2022',
        likes: 100,
        autorName:'Shon Pozner',
        url: 'https://www.google.com/',
    },
    {
        id: 6,
        favorite: true,
        imgUrl: img2,
        title: 'Zoom',
        tags: ['sport', 'football', 'pop'],
        createdTime:'16/11/2021',
        editTime: '1/1/2022',
        likes: 100,
        autorName:'Shon Pozner',
        url: 'https://us02web.zoom.us/rec/play/E38eBi_rfsgGCYhh6YiiutEw4pcsdCsHF2jy0sOMCfEAEzoFrb4z0IBnQLf5jgsMRxqULz7h-5fpc5S3.tLHdrPTcTXQ2n0Tz?continueMode=true&_x_zm_rtaid=8E8g3kSeQMGVoTvDaygrrQ.1603012922993.2fcaba7a7c5cc81110b378f2474fb863&_x_zm_rhtaid=614',
    },
    {
        id: 7,
        favorite: true,
        imgUrl: img3,
        title: 'My first card!',
        tags: ['sport', 'zoom', 'imp','shon4me@gmail', 'fdasfads'],
        createdTime:'16/11/2021',
        editTime: '1/1/2022',
        likes: 100,
        autorName:'Shon Pozner',
        url: 'https://www.google.com',
    },

    {
        id: 8,
        favorite: true,
        imgUrl: img4,
        title: 'My first card!',
        tags: ['sport', 'zoom'],
        createdTime:'16/11/2021',
        editTime: '1/1/2022',
        likes: 100,
        autorName:'Shon Pozner',
        url: 'https://www.google.com/',
    },
    {
        id: 9,
        favorite: true,
        imgUrl: img1,
        title: 'My first card!',
        tags: ['Todo'],
        createdTime:'16/11/2021',
        editTime: '1/1/2022',
        likes: 100,
        autorName:'Shon Pozner',
        url: 'https://www.google.com/',
    },
    {
        id: 11,
        favorite: true,
        imgUrl: img2,
        title: 'Zoom',
        tags: ['sport', 'football', 'pop'],
        createdTime:'16/11/2021',
        editTime: '1/1/2022',
        likes: 100,
        autorName:'Shon Pozner',
        url: 'https://us02web.zoom.us/rec/play/E38eBi_rfsgGCYhh6YiiutEw4pcsdCsHF2jy0sOMCfEAEzoFrb4z0IBnQLf5jgsMRxqULz7h-5fpc5S3.tLHdrPTcTXQ2n0Tz?continueMode=true&_x_zm_rtaid=8E8g3kSeQMGVoTvDaygrrQ.1603012922993.2fcaba7a7c5cc81110b378f2474fb863&_x_zm_rhtaid=614',
    },
    {
        id: 12,
        favorite: true,
        imgUrl: img3,
        title: 'My first card!',
        tags: ['sport', 'zoom', 'imp','shon4me@gmail', 'fdasfads'],
        createdTime:'16/11/2021',
        editTime: '1/1/2022',
        likes: 100,
        autorName:'Shon Pozner',
        url: 'https://www.google.com',
    },

    {
        id: 13,
        favorite: true,
        imgUrl: img4,
        title: 'My first card!',
        tags: ['sport', 'zoom'],
        createdTime:'16/11/2021',
        editTime: '1/1/2022',
        likes: 100,
        autorName:'Shon Pozner',
        url: 'https://www.google.com/',
    },
    {
        id: 14,
        favorite: true,
        imgUrl: img1,
        title: 'My first card!',
        tags: ['Todo'],
        createdTime:'16/11/2021',
        editTime: '1/1/2022',
        likes: 100,
        autorName:'Shon Pozner',
        url: 'https://www.google.com/',
    },
    {
        id: 15,
        favorite: true,
        imgUrl: img2,
        title: 'Zoom',
        tags: ['sport', 'football', 'pop'],
        createdTime:'16/11/2021',
        editTime: '1/1/2022',
        likes: 100,
        autorName:'Shon Pozner',
        url: 'https://us02web.zoom.us/rec/play/E38eBi_rfsgGCYhh6YiiutEw4pcsdCsHF2jy0sOMCfEAEzoFrb4z0IBnQLf5jgsMRxqULz7h-5fpc5S3.tLHdrPTcTXQ2n0Tz?continueMode=true&_x_zm_rtaid=8E8g3kSeQMGVoTvDaygrrQ.1603012922993.2fcaba7a7c5cc81110b378f2474fb863&_x_zm_rhtaid=614',
    },
    {
        id: 16,
        favorite: true,
        imgUrl: img3,
        title: 'My first card!',
        tags: ['sport', 'zoom', 'imp','shon4me@gmail', 'fdasfads'],
        createdTime:'16/11/2021',
        editTime: '1/1/2022',
        likes: 100,
        autorName:'Shon Pozner',
        url: 'https://www.google.com',
    },

    {
        id: 17,
        favorite: true,
        imgUrl: img4,
        title: 'My first card!',
        tags: ['sport', 'zoom'],
        createdTime:'16/11/2021',
        editTime: '1/1/2022',
        likes: 100,
        autorName:'Shon Pozner',
        url: 'https://www.google.com/',
    },
]